changelog:
  exclude:
    labels:
      - ignore-for-release
      - devops
      - testing
      - dependencies
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - feature
        - client
        - server
      
