# Note: When running locally through `act` package and in order to verify the exposed artifacts,
# I need to supply the `--artifact-serve-path` option with a valid local path to save them.
#
# @example: sudo act --artifact-server-path ./tmp/artifacts
#
# @source: https://github.com/nektos/act/issues/329#issuecomment-1187246629
#

name: Estiator.io CI/CD pipeline
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('client/package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        working-directory: ./client
        run: npm ci --ignore-scripts
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('client/package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        working-directory: ./client
        run: npm ci --ignore-scripts
      - name: Build application
        working-directory: ./client
        run: npm run build
      - name: Create and upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: estiator.io_build_${{ github.run_id }}
          path: ./client/dist/